name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: windows_amd64
            output: snek.exe
          - os: ubuntu-latest
            target: linux_amd64
            output: snek_linux
          - os: macos-latest
            target: darwin_arm64
            output: snek_macos_arm
          - os: macos-latest
            target: darwin_amd64
            output: snek_macos_intel

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: laytan/setup-odin@v2

      - run: odin version
        shell: bash

      - run: odin build source -target:${{ matrix.target }} -out:out/${{ matrix.output }}
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output }}
          path: out/${{ matrix.output }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}